baseURL = "https://who.isdotdot.com/"
languageCode = "en-us"
title = "Who People Are"
paginate = 10

[params]
  siteDescription = "Short profiles and quick histories answering 'Who is...?' questions."
